# Generated by Django 4.2.4 on 2026-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0008_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='review',
            name='liked',
            field=models.BooleanField(null=True, verbose_name='приобрел(-а) бы еще раз?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '💔'), (2, '💛💛'), (3, '🧡🧡🧡'), (4, '\U0001fa77\U0001fa77\U0001fa77\U0001fa77'), (5, '❤️❤️❤️❤️❤️️')], verbose_name='рейтинг'),
        ),
    ]
