# Generated by Django 5.2.12 on 2026-08-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0011_publish_existing_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
