# Generated by Django 5.2.12 on 2026-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0012_delete_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='краткое описание'),
        ),
    ]
