# Generated by Django 5.2.17 on 2026-10-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosapp', '0014_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('PLN', 'zł'), ('EUR', '€'), ('USD', '$'), ('GBP', '£'), ('RUB', '₽')], default='PLN', max_length=3, verbose_name='валюта'),
        ),
    ]
